version: 2

sources:
  - name: chicago_taxi
    description: >
      Public Chicago Taxi Trips dataset provided by the City of Chicago
      and available through the BigQuery public datasets.
    database: bigquery-public-data
    schema: chicago_taxi_trips

    tables:
      - name: taxi_trips
        description: >
          Taxi trip records reported to the City of Chicago.